import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screenContainer: {
    backgroundColor: '#F3F1FF',
    paddingBottom: 40,
    alignItems: 'center',
  },
  card: {
    width: '92%',
    backgroundColor: '#FFF',
    borderRadius: 32,
    padding: 28,
    marginTop: 40,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
    alignItems: 'center',
  },
  voltarBtn: {
    position: 'absolute',
    top: 22,
    left: 22,
    width: 44,
    height: 44,
    backgroundColor: '#F3F3FF',
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  voltarIcon: {
    fontSize: 18,
    color: '#6B7280',
  },
  logo: {
    width: 90,
    height: 90,
    marginBottom: 18,
  },
  titulo: {
    color: '#0D214F',
    fontWeight: 'bold',
    fontSize: 26,
    marginBottom: 8,
  },
  subtitulo: {
    color: '#7E869E',
    textAlign: 'center',
    marginBottom: 24,
    fontSize: 14,
    lineHeight: 22,
  },
  labelInput: {
    color: '#7E869E',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  input: {
    width: '100%',
    backgroundColor: '#F8F8FF',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#ECECF7',
    paddingHorizontal: 18,
    paddingVertical: 14,
    marginBottom: 16,
    color: '#18264B',
    fontSize: 15,
  },
  senhaLabel: {
    color: '#7E869E',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
    alignSelf: 'flex-start',
  },
  senhaRequisito: {
    color: '#A0A7BA',
    fontSize: 12,
    marginBottom: 4,
    alignSelf: 'flex-start',
  },
  requisitoAtivo: {
    color: '#9127E1',
  },
  botao: {
    width: '100%',
    backgroundColor: '#9127E1',
    paddingVertical: 16,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 18,
  },
  textoBotao: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  footerText: {
    color: '#7E869E',
    fontSize: 14,
  },
  footerLink: {
    color: '#9127E1',
    fontWeight: '700',
  },
});

