import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screenContainer: {
    flexGrow: 1,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 28,
  },
  screenContainerDark: {
    backgroundColor: '#1B2134',
  },
  card: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 34,
    paddingTop: 28,
    paddingBottom: 36,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  cardDark: {
    backgroundColor: '#252B3F',
    borderColor: '#3A435D',
    shadowOpacity: 0.18,
    elevation: 3,
  },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    paddingVertical: 6,
    marginBottom: 12,
  },
  backText: {
    color: '#26344D',
    fontSize: 14,
    fontWeight: '700',
  },
  backTextDark: {
    color: '#FFFFFF',
  },
  title: {
    fontSize: 31,
    lineHeight: 37,
    fontWeight: '900',
    color: '#071226',
    textAlign: 'center',
    marginBottom: 6,
  },
  titleDark: {
    color: '#FFFFFF',
  },
  subtitle: {
    alignSelf: 'center',
    maxWidth: 390,
    fontSize: 14,
    lineHeight: 20,
    color: '#26344D',
    textAlign: 'center',
    marginBottom: 38,
  },
  subtitleDark: {
    color: '#D6DEFF',
  },
  codeRow: {
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    columnGap: 14,
    marginBottom: 34,
  },
  codeBox: {
    width: 58,
    height: 72,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DDE3EC',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0F172A',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  codeBoxDark: {
    backgroundColor: '#30374F',
    borderColor: '#4A5570',
    shadowOpacity: 0.12,
    elevation: 2,
  },
  codeBoxFilled: {
    borderColor: '#8B13DB',
    backgroundColor: '#FBF7FF',
  },
  codeBoxFilledDark: {
    backgroundColor: '#2B2144',
    borderColor: '#A855F7',
  },
  codeText: {
    fontSize: 24,
    fontWeight: '900',
    color: '#071226',
  },
  codeTextDark: {
    color: '#FFFFFF',
  },
  hiddenInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  resendButton: {
    alignSelf: 'center',
    paddingVertical: 8,
    marginBottom: 28,
  },
  resendText: {
    color: '#334155',
    fontWeight: '800',
    fontSize: 14,
  },
  resendTextDark: {
    color: '#FFFFFF',
  },
  button: {
    width: '100%',
    height: 44,
    backgroundColor: '#8B13DB',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 34,
  },
  buttonDisabled: {
    opacity: 0.72,
  },
  buttonText: {
    color: '#FFF',
    fontWeight: '900',
    fontSize: 15,
  },
  footerText: {
    color: '#334155',
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
  },
  footerTextDark: {
    color: '#D6DEFF',
  },
});
