import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FD',
  },
  container: {
    paddingTop: 35,
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  // CONTEÚDO COM SCROLL - Ajustado para o respiro perfeito abaixo do Header
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,        
    paddingBottom: 120,    
  },
  // CARD PRINCIPAL DO PET
  profileCard: {
    backgroundColor: '#FFF',
    borderRadius: 35,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 15,
  },
  petImageWrapper: {
    width: '100%',
    height: 220,
    borderRadius: 25,
    marginBottom: 15,
    overflow: 'hidden',
    position: 'relative',
  },
  petImg: {
    width: '100%',
    height: 220,
    borderRadius: 25,
  },
  petCameraBadge: {
    position: 'absolute',
    right: 14,
    bottom: 14,
    width: 38,
    height: 38,
    borderRadius: 14,
    backgroundColor: '#9127E1',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  nameWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  petName: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#0D214F',
  },
  petBreed: {
    fontSize: 14,
    color: '#A0A7BA',
    fontWeight: '600',
    marginBottom: 20,
  },
  // CAIXAS DE PESO E SEXO
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  statBox: {
    width: '48%',
    height: 80,
    borderRadius: 20,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statLabel: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  sexSelectButton: {
    minHeight: 34,
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sexSelectText: {
    flex: 1,
    fontSize: 16,
    fontWeight: 'bold',
  },
  sexModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 18,
    paddingBottom: 18,
  },
  sexModalSheet: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  sexModalTitle: {
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 14,
  },
  sexModalOption: {
    minHeight: 54,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
    justifyContent: 'center',
    marginBottom: 10,
  },
  sexModalOptionText: {
    fontSize: 16,
    fontWeight: '800',
  },
  sexModalCancel: {
    height: 48,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  sexModalCancelText: {
    fontSize: 13,
    fontWeight: '900',
  },
  // CARD PRÓXIMA CONSULTA (ROXO)
  appointmentCard: {
    backgroundColor: '#9127E1',
    borderRadius: 30,
    padding: 22,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#9127E1',
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  appointmentLabel: {
    color: '#E8D5F7',
    fontSize: 13,
    fontWeight: '700',
  },
  appointmentDate: {
    color: '#FFF',
    fontSize: 28,
    fontWeight: 'bold',
  },
  appointmentType: {
    color: '#FFF',
    fontSize: 15,
    opacity: 0.9,
  },
  // SEÇÃO DE CONTEÚDO (SOBRE / SAÚDE / MEDICAMENTOS)
  contentCard: {
    backgroundColor: '#FFF',
    borderRadius: 35,
    padding: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.03,
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: '#F3F5F9',
    borderRadius: 18,
    padding: 5,
    marginBottom: 25,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 15,
  },
  tabBtnActive: {
    backgroundColor: '#9127E1',
  },
  tabText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#7E869E',
  },
  tabTextActive: {
    color: '#FFF',
  },
  // ESTILOS DE FORMULÁRIO
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0D214F',
    marginBottom: 10,
  },
  labelUpper: {
    fontSize: 11,
    fontWeight: '800',
    color: '#A0A7BA',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 5,
  },
  textInput: {
    backgroundColor: '#F9FAFB',
    borderRadius: 15,
    padding: 15,
    fontSize: 15,
    color: '#4A5568',
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  textArea: {
    height: 110,
    textAlignVertical: 'top',
  },
  rowInputs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  // VACINAÇÃO (ABA SAÚDE)
  vaccineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#FFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F1F1F1',
    marginBottom: 12,
  },
  vaccineCircle: {
    width: 45,
    height: 45,
    borderRadius: 15,
    backgroundColor: '#F5E6FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  vaccineInfo: {
    flex: 1,
    marginLeft: 15,
  },
  vaccineName: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#0D214F',
  },
  nextDoseBox: {
    alignItems: 'flex-end',
  },
  // CRONOGRAMA (ABA MEDICAMENTOS)
  periodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    marginTop: 10,
    gap: 10,
  },
  periodTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0D214F',
  },
  countBadge: {
    backgroundColor: '#F3F5F9',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    fontSize: 10,
    color: '#7E869E',
    fontWeight: 'bold',
  },
  medicCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 18,
    borderLeftWidth: 6,
    marginBottom: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  medicHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  medicTime: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0D214F',
  },
  petBadgeMedic: {
    backgroundColor: '#F5E6FF',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  petBadgeMedicText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#9127E1',
    textTransform: 'uppercase',
  },
  medicName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4A5568',
  },
  instructionBox: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
  },
  instructionText: {
    fontSize: 13,
    color: '#7E869E',
  },
  // BOTÃO SALVAR GERAL
  btnSave: {
    backgroundColor: '#9127E1',
    height: 60,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    elevation: 4,
  },
  btnSaveText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  vaccineModalOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  vaccineModalCard: {
    borderRadius: 28,
    paddingHorizontal: 26,
    paddingTop: 30,
    paddingBottom: 26,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  vaccineModalIcon: {
    width: 64,
    height: 64,
    borderRadius: 18,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  vaccineModalEmoji: {
    fontSize: 28,
  },
  vaccineModalTitle: {
    fontSize: 25,
    fontWeight: '900',
    textAlign: 'center',
  },
  vaccineModalSubtitle: {
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 5,
    marginBottom: 30,
  },
  vaccineModalInput: {
    height: 60,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 18,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 16,
  },
  vaccineDateInputWrapper: {
    height: 60,
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  vaccineDateInput: {
    flex: 1,
    height: '100%',
    fontSize: 15,
    fontWeight: '800',
  },
  vaccineModalActions: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 16,
  },
  vaccineCancelButton: {
    flex: 1,
    height: 48,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vaccineCancelText: {
    fontSize: 13,
    fontWeight: '900',
  },
  vaccineSaveButton: {
    flex: 1,
    height: 48,
    borderRadius: 15,
    backgroundColor: '#A020F0',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#9127E1',
    shadowOpacity: 0.28,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
  },
  vaccineSaveButtonDisabled: {
    opacity: 0.7,
  },
  vaccineSaveText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '900',
  },
});
