import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FD',
  },
  chatContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 24,
  },
  sectionHeader: {
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#0D214F',
  },
  subtitle: {
    fontSize: 14,
    color: '#7E869E',
    marginTop: 4,
  },
  conversaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 15,
    marginBottom: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  avatar: {
    width: 55,
    height: 55,
    borderRadius: 18,
    backgroundColor: '#F3F5F9',
  },
  conversaInfo: {
    flex: 1,
    marginLeft: 15,
  },
  conversaNome: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0D214F',
  },
  conversaSubtitulo: {
    fontSize: 13,
    color: '#7E869E',
    marginTop: 2,
  },
  verPerfilBtn: {
    backgroundColor: '#F5E6FF',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 15,
  },
  verPerfilText: {
    color: '#9127E1',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  messageReceived: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF',
    paddingVertical: 14,
    paddingHorizontal: 15,
    borderRadius: 20,
    borderBottomLeftRadius: 5,
    marginBottom: 15,
    maxWidth: '80%',
    elevation: 2,
  },
  chatFooter: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 16,
    backgroundColor: '#F8F9FD',
    borderTopWidth: 1,
    borderTopColor: '#EDF0F5',
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#FFF',
    borderRadius: 28,
    paddingHorizontal: 15,
    minHeight: 60,
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 15,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  input: {
    flex: 1,
    color: '#4A5568',
    fontSize: 15,
    paddingVertical: 14,
    minHeight: 24,
  },
  botaoEnviar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#9127E1',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    marginBottom: 6,
  },
  empty: {
    textAlign: 'center',
    color: '#A0A7BA',
    marginTop: 50,
  },
});
