import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screenContainer: {
    flexGrow: 1,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 28,
  },
  screenContainerDark: {
    backgroundColor: '#1B2134',
  },
  card: {
    width: '100%',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 36,
    paddingTop: 28,
    paddingBottom: 36,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  cardDark: {
    backgroundColor: '#252B3F',
    borderColor: '#3A435D',
    shadowOpacity: 0.18,
    elevation: 3,
  },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    paddingVertical: 6,
    marginBottom: 8,
  },
  backText: {
    color: '#26344D',
    fontSize: 14,
    fontWeight: '700',
  },
  backTextDark: {
    color: '#FFFFFF',
  },
  iconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#8B13DB',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  title: {
    fontSize: 31,
    lineHeight: 37,
    fontWeight: '900',
    color: '#071226',
    textAlign: 'center',
    marginBottom: 4,
  },
  titleDark: {
    color: '#FFFFFF',
  },
  subtitle: {
    fontSize: 13,
    color: '#26344D',
    textAlign: 'center',
    marginBottom: 30,
  },
  subtitleDark: {
    color: '#D6DEFF',
  },
  label: {
    color: '#172033',
    fontSize: 11,
    fontWeight: '900',
    marginBottom: 9,
  },
  labelDark: {
    color: '#FFFFFF',
  },
  inputWrap: {
    width: '100%',
    height: 54,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#DDE3EC',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  inputWrapDark: {
    backgroundColor: '#30374F',
    borderColor: '#4A5570',
  },
  input: {
    flex: 1,
    height: '100%',
    paddingLeft: 14,
    paddingRight: 8,
    color: '#172033',
    fontSize: 15,
  },
  inputDark: {
    color: '#FFFFFF',
  },
  eyeButton: {
    width: 46,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    width: '100%',
    height: 44,
    backgroundColor: '#8B13DB',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  buttonDisabled: {
    opacity: 0.72,
  },
  buttonText: {
    color: '#FFF',
    fontWeight: '900',
    fontSize: 15,
  },
});
